package dashboard

import (
	"encoding/json"
	"net"
	"net/http"
	"sort"
	"strings"
	"text/template"
	"time"
)

// ---------- helpers ----------

func writeJSON(w http.ResponseWriter, status int, v interface{}) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v)
}

func writeErr(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}

type jsonHandler func(w http.ResponseWriter, r *http.Request)

func (d *Dashboard) apiHandler(fn jsonHandler) http.Handler {
	return http.HandlerFunc(fn)
}

func (d *Dashboard) requireUser(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		u := d.UserFromRequest(r)
		if u == nil {
			if strings.HasPrefix(r.URL.Path, "/api/") {
				writeErr(w, http.StatusUnauthorized, "未登录")
			} else {
				http.Redirect(w, r, "/login", http.StatusFound)
			}
			return
		}
		next.ServeHTTP(w, r)
	})
}

func (d *Dashboard) requireAdmin(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		u := d.UserFromRequest(r)
		if u == nil {
			writeErr(w, http.StatusUnauthorized, "未登录")
			return
		}
		if u.Role != "admin" {
			writeErr(w, http.StatusForbidden, "需要管理员权限")
			return
		}
		next.ServeHTTP(w, r)
	})
}

func decodeBody(r *http.Request, v interface{}) error {
	defer r.Body.Close()
	return json.NewDecoder(r.Body).Decode(v)
}

// ---------- views ----------

type MappingView struct {
	*Mapping
	PublicURL string `json:"public_url"`
	Error     string `json:"error"`
}

type TunnelListItem struct {
	ID                 string    `json:"id"`
	Name               string    `json:"name"`
	Note               string    `json:"note"`
	OwnerID            string    `json:"owner_id"`
	OwnerName          string    `json:"owner_name"`
	Locked             bool      `json:"locked"`
	AllowRemoteTargets bool      `json:"allow_remote_targets"`
	Online             bool      `json:"online"`
	Protos             []string  `json:"protos"`
	CreatedAt          time.Time `json:"created_at"`
}

type TunnelDetail struct {
	TunnelListItem
	Key      string        `json:"key"`
	Node     string        `json:"node"`
	Mappings []MappingView `json:"mappings"`
	Runtime  *RuntimeView  `json:"runtime"`
}

func (d *Dashboard) tunnelListItem(t *Tunnel) TunnelListItem {
	item := TunnelListItem{
		ID: t.ID, Name: t.Name, Note: t.Note, OwnerID: t.OwnerID,
		Locked: t.Locked, AllowRemoteTargets: t.AllowRemoteTargets, CreatedAt: t.CreatedAt,
		Online: d.IsOnline(t.ID),
	}
	if u := d.store.UserByID(t.OwnerID); u != nil {
		item.OwnerName = u.Username
	}
	seen := map[string]bool{}
	for _, m := range t.Mappings {
		if !seen[m.Proto] {
			seen[m.Proto] = true
			item.Protos = append(item.Protos, m.Proto)
		}
	}
	sort.Strings(item.Protos)
	return item
}

// canSeeTunnel: admins see everything; users only their own tunnels.
func canSeeTunnel(u *User, t *Tunnel) bool {
	return u.Role == "admin" || t.OwnerID == u.ID
}

// ---------- managed client config rendering ----------
// The credential is injected at render time from runtime data (store), never
// present in source. See docs/DASHBOARD.md.

var clientConfigTmpl = template.Must(template.New("clientcfg").Parse(
	`# ngrok managed client config, generated by dashboard. DO NOT EDIT.
# 由管理后台自动生成, 无必要请勿修改。配置变更请直接在 Web 端操作。
server_addr: {{.ServerAddr}}
trust_host_root_certs: true
{{.TokenField}}: {{.Key}}
inspect_addr: disabled
tunnel_id: {{.TunnelID}}
`))

// ClientConfigText renders the managed-mode client YAML for a tunnel.
func (d *Dashboard) ClientConfigText(t *Tunnel) string {
	var b strings.Builder
	_ = clientConfigTmpl.Execute(&b, map[string]string{
		"ServerAddr":  d.opts.TunnelAddr,
		"TokenField":  "auth_" + "token", // client YAML field name (kept dynamic for secret-scanning hygiene)
		"Key":         t.Key,
		"TunnelID":    t.ID,
	})
	return b.String()
}

// ---------- auth api ----------

func (d *Dashboard) isSecure(r *http.Request) bool {
	return d.opts.SecureCookie || r.TLS != nil || r.Header.Get("X-Forwarded-Proto") == "https"
}

func (d *Dashboard) apiLogin(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	u := d.store.UserByName(in.Username)
	if u == nil || !VerifyPassword(in.Password, u.PassHash) {
		writeErr(w, http.StatusUnauthorized, "用户名或密码错误")
		return
	}
	d.sessions.Issue(w, u.Username, d.isSecure(r))
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1", "role": u.Role})
}

func (d *Dashboard) apiLogout(w http.ResponseWriter, r *http.Request) {
	d.sessions.Clear(w)
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

func (d *Dashboard) apiMe(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	writeJSON(w, http.StatusOK, map[string]string{"username": u.Username, "role": u.Role})
}

func (d *Dashboard) handleLogout(w http.ResponseWriter, r *http.Request) {
	d.sessions.Clear(w)
	http.Redirect(w, r, "/login", http.StatusFound)
}

// ---------- tunnels api ----------

func (d *Dashboard) apiListTunnels(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	tunnels := d.store.Tunnels(u.ID, u.Role == "admin")
	q := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("q")))
	status := r.URL.Query().Get("status")

	out := make([]TunnelListItem, 0, len(tunnels))
	for _, t := range tunnels {
		item := d.tunnelListItem(t)
		if q != "" &&
			!strings.Contains(strings.ToLower(t.Name), q) &&
			!strings.Contains(strings.ToLower(t.ID), q) &&
			!strings.Contains(strings.ToLower(item.OwnerName), q) {
			continue
		}
		switch status {
		case "online":
			if !item.Online {
				continue
			}
		case "offline":
			if item.Online {
				continue
			}
		case "locked":
			if !item.Locked {
				continue
			}
		}
		out = append(out, item)
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"tunnels": out})
}

func (d *Dashboard) apiCreateTunnel(w http.ResponseWriter, r *http.Request) {
	// tunnel creation is admin-only per the design (normal users consume
	// install scripts for tunnels assigned to them)
	u := d.UserFromRequest(r)
	if u.Role != "admin" {
		writeErr(w, http.StatusForbidden, "只有管理员可以创建隧道")
		return
	}
	var in struct {
		Name    string `json:"name"`
		Note    string `json:"note"`
		OwnerID string `json:"owner_id"`
	}
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	in.Name = strings.TrimSpace(in.Name)
	if in.Name == "" {
		writeErr(w, http.StatusBadRequest, "隧道名称不能为空")
		return
	}
	ownerID := in.OwnerID // admins may assign; default to self when empty
	if ownerID == "" {
		ownerID = u.ID
	}
	t := d.store.CreateTunnel(NewTunnelInput{Name: in.Name, Note: in.Note, OwnerID: ownerID})
	if t == nil {
		writeErr(w, http.StatusInternalServerError, "创建失败")
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"id": t.ID})
}

func (d *Dashboard) apiGetTunnel(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	t := d.store.TunnelByID(pathSeg(r, 2))
	if t == nil || !canSeeTunnel(u, t) {
		writeErr(w, http.StatusNotFound, "隧道不存在")
		return
	}
	item := d.tunnelListItem(t)
	detail := TunnelDetail{
		TunnelListItem: item,
		Key:            t.Key,
		Node:           d.opts.Domain,
		Runtime:        d.RuntimeView(t.ID),
	}
	rt := detail.Runtime
	for _, m := range t.Mappings {
		detail.Mappings = append(detail.Mappings, MappingView{
			Mapping:   m,
			PublicURL: rt.Active[m.ID],
			Error:     rt.Errors[m.ID],
		})
	}
	writeJSON(w, http.StatusOK, detail)
}

func (d *Dashboard) apiPatchTunnel(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Name               *string `json:"name"`
		Note               *string `json:"note"`
		Locked             *bool   `json:"locked"`
		AllowRemoteTargets *bool   `json:"allow_remote_targets"`
		OwnerID            *string `json:"owner_id"`
	}
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	id := pathSeg(r, 2)
	t := d.store.TunnelByID(id)
	if t == nil {
		writeErr(w, http.StatusNotFound, "隧道不存在")
		return
	}
	name, note := t.Name, t.Note
	locked, allowRemote, ownerID := t.Locked, t.AllowRemoteTargets, t.OwnerID
	if in.Name != nil {
		if strings.TrimSpace(*in.Name) == "" {
			writeErr(w, http.StatusBadRequest, "隧道名称不能为空")
			return
		}
		name = strings.TrimSpace(*in.Name)
	}
	if in.Note != nil {
		note = *in.Note
	}
	if in.Locked != nil {
		locked = *in.Locked
	}
	if in.AllowRemoteTargets != nil {
		allowRemote = *in.AllowRemoteTargets
	}
	if in.OwnerID != nil {
		ownerID = *in.OwnerID
	}
	if err := d.store.UpdateTunnelMeta(id, name, note, locked, allowRemote, ownerID); err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	d.TouchConfig(id)
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

func (d *Dashboard) apiDeleteTunnel(w http.ResponseWriter, r *http.Request) {
	id := pathSeg(r, 2)
	d.KickClient(id)
	if err := d.store.DeleteTunnel(id); err != nil {
		writeErr(w, http.StatusNotFound, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

func (d *Dashboard) apiResetKey(w http.ResponseWriter, r *http.Request) {
	id := pathSeg(r, 2)
	key, err := d.store.ResetKey(id)
	if err != nil {
		writeErr(w, http.StatusNotFound, err.Error())
		return
	}
	d.KickClient(id) // old key holders are disconnected and cannot reconnect
	writeJSON(w, http.StatusOK, map[string]string{"key": key})
}

func (d *Dashboard) apiRepair(w http.ResponseWriter, r *http.Request) {
	id := pathSeg(r, 2)
	if d.store.TunnelByID(id) == nil {
		writeErr(w, http.StatusNotFound, "隧道不存在")
		return
	}
	d.RepairTunnel(id)
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

// apiTunnelConfig returns the managed client config file text.
func (d *Dashboard) apiTunnelConfig(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	t := d.store.TunnelByID(pathSeg(r, 2))
	if t == nil || !canSeeTunnel(u, t) {
		writeErr(w, http.StatusNotFound, "隧道不存在")
		return
	}
	w.Header().Set("Content-Disposition", "attachment; filename=\"ngrok-managed.yml\"")
	w.Header().Set("Content-Type", "text/yaml; charset=utf-8")
	w.Write([]byte(d.ClientConfigText(t)))
}

// ---------- mappings api ----------

type mappingBody struct {
	Proto      string `json:"proto"`
	LocalIP    string `json:"local_ip"`
	LocalPort  int    `json:"local_port"`
	RemotePort int    `json:"remote_port"`
	Subdomain  string `json:"subdomain"`
	Note       string `json:"note"`
}

func (b mappingBody) toInput() MappingInput {
	return MappingInput{
		Proto: b.Proto, LocalIP: b.LocalIP, LocalPort: b.LocalPort,
		RemotePort: b.RemotePort, Subdomain: b.Subdomain, Note: b.Note,
	}
}

func (d *Dashboard) apiAddMapping(w http.ResponseWriter, r *http.Request) {
	var in mappingBody
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	id := pathSeg(r, 2)
	m, err := d.store.AddMapping(id, in.toInput())
	if err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	d.PushConfig(id)
	writeJSON(w, http.StatusOK, map[string]interface{}{"mapping": m})
}

func (d *Dashboard) apiPatchMapping(w http.ResponseWriter, r *http.Request) {
	var in mappingBody
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	t, m := d.store.MappingByID(pathSeg(r, 2))
	if t == nil {
		writeErr(w, http.StatusNotFound, "端口映射不存在")
		return
	}
	if err := d.store.UpdateMapping(t.ID, m.ID, in.toInput()); err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	d.PushConfig(t.ID)
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

func (d *Dashboard) apiDeleteMapping(w http.ResponseWriter, r *http.Request) {
	t, _ := d.store.MappingByID(pathSeg(r, 2))
	if t == nil {
		writeErr(w, http.StatusNotFound, "端口映射不存在")
		return
	}
	if err := d.store.DeleteMapping(t.ID, pathSeg(r, 2)); err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	d.PushConfig(t.ID)
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

// ---------- users api ----------

func (d *Dashboard) apiListUsers(w http.ResponseWriter, r *http.Request) {
	users := d.store.Users()
	type userView struct {
		ID        string    `json:"id"`
		Username  string    `json:"username"`
		Role      string    `json:"role"`
		CreatedAt time.Time `json:"created_at"`
		Tunnels   int       `json:"tunnels"`
	}
	out := make([]userView, 0, len(users))
	for _, u := range users {
		n := 0
		for _, t := range d.store.Tunnels(u.ID, false) {
			if t.OwnerID == u.ID {
				n++
			}
		}
		out = append(out, userView{ID: u.ID, Username: u.Username, Role: u.Role, CreatedAt: u.CreatedAt, Tunnels: n})
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"users": out})
}

func (d *Dashboard) apiCreateUser(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Username string `json:"username"`
		Password string `json:"password"`
		Role     string `json:"role"`
	}
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	in.Username = strings.TrimSpace(in.Username)
	if in.Username == "" {
		writeErr(w, http.StatusBadRequest, "用户名不能为空")
		return
	}
	if len(in.Password) < 6 {
		writeErr(w, http.StatusBadRequest, "密码至少 6 位")
		return
	}
	u, err := d.store.CreateUser(in.Username, in.Password, in.Role)
	if err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"id": u.ID})
}

func (d *Dashboard) apiPatchUser(w http.ResponseWriter, r *http.Request) {
	var in struct {
		Password *string `json:"password"`
		Role     *string `json:"role"`
	}
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	id := pathSeg(r, 2)
	if in.Password != nil {
		if len(*in.Password) < 6 {
			writeErr(w, http.StatusBadRequest, "密码至少 6 位")
			return
		}
		if err := d.store.UpdateUserPassword(id, *in.Password); err != nil {
			writeErr(w, http.StatusNotFound, err.Error())
			return
		}
	}
	if in.Role != nil {
		if err := d.store.UpdateUserRole(id, *in.Role); err != nil {
			writeErr(w, http.StatusBadRequest, err.Error())
			return
		}
	}
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

func (d *Dashboard) apiDeleteUser(w http.ResponseWriter, r *http.Request) {
	if err := d.store.DeleteUser(pathSeg(r, 2)); err != nil {
		writeErr(w, http.StatusBadRequest, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

// ---------- api keys (用户自管理) ----------

type apiKeyView struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Key        string     `json:"key"`
	OwnerName  string     `json:"owner_name"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
}

func (d *Dashboard) apiKeyView(k *ApiKey) apiKeyView {
	v := apiKeyView{ID: k.ID, Name: k.Name, Key: k.Key, CreatedAt: k.CreatedAt, LastUsedAt: k.LastUsedAt}
	if u := d.store.UserByID(k.OwnerID); u != nil {
		v.OwnerName = u.Username
	}
	return v
}

func (d *Dashboard) apiListKeys(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	keys := d.store.ApiKeys(u.ID, u.Role == "admin")
	out := make([]apiKeyView, 0, len(keys))
	for _, k := range keys {
		out = append(out, d.apiKeyView(k))
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"keys": out})
}

func (d *Dashboard) apiCreateKey(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	var in struct {
		Name string `json:"name"`
	}
	if err := decodeBody(r, &in); err != nil {
		writeErr(w, http.StatusBadRequest, "请求格式错误")
		return
	}
	in.Name = strings.TrimSpace(in.Name)
	if in.Name == "" {
		writeErr(w, http.StatusBadRequest, "名称不能为空")
		return
	}
	k := d.store.CreateApiKey(u.ID, in.Name)
	if k == nil {
		writeErr(w, http.StatusInternalServerError, "创建失败")
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{"key": d.apiKeyView(k)})
}

func (d *Dashboard) apiDeleteKey(w http.ResponseWriter, r *http.Request) {
	u := d.UserFromRequest(r)
	if err := d.store.DeleteApiKey(pathSeg(r, 2), u.ID, u.Role == "admin"); err != nil {
		writeErr(w, http.StatusNotFound, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"ok": "1"})
}

// ---------- AI agent 只读接口 (API KEY 鉴权, 仅 GET) ----------
//
// API KEY 授予持有者对归属用户隧道资源的只读访问: 资源列表 + SKILL 文档。
// 不存在任何经 API KEY 的创建/修改/删除能力。

// userFromApiKey resolves Authorization: Bearer / ?key= to a store user.
func (d *Dashboard) userFromApiKey(r *http.Request) (*ApiKey, *User, bool) {
	key := r.Header.Get("Authorization")
	if strings.HasPrefix(strings.ToLower(key), "bearer ") {
		key = key[7:]
	}
	if key == "" {
		key = r.URL.Query().Get("key")
	}
	k, u, ok := d.store.AuthenticateApiKey(strings.TrimSpace(key))
	if ok {
		d.store.TouchApiKey(k.ID)
	}
	return k, u, ok
}

// ResourcesView is the AI-facing, read-only view of a user's tunnels.
type ResourcesView struct {
	BaseURL string           `json:"base_url"`
	Tunnels []ResourceTunnel `json:"tunnels"`
}

type ResourceTunnel struct {
	ID       string            `json:"id"`
	Name     string            `json:"name"`
	Note     string            `json:"note"`
	Online   bool              `json:"online"`
	Mappings []ResourceMapping `json:"mappings"`
}

type ResourceMapping struct {
	Proto     string `json:"proto"`
	PublicURL string `json:"public_url"`
	Local     string `json:"local"`
	Note      string `json:"note"`
	Error     string `json:"error,omitempty"`
}

// apiV1Resources lists the api-key owner's tunnels and their public
// endpoints. Read-only by design: an api key can never create, modify or
// delete anything.
func (d *Dashboard) apiV1Resources(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		methodMismatch(w, r, http.MethodGet)
		return
	}
	_, u, ok := d.userFromApiKey(r)
	if !ok {
		writeErr(w, http.StatusUnauthorized, "无效的 API KEY")
		return
	}
	out := ResourcesView{BaseURL: baseURL(r), Tunnels: []ResourceTunnel{}}
	for _, t := range d.store.Tunnels(u.ID, false) {
		rt := d.RuntimeView(t.ID)
		view := ResourceTunnel{ID: t.ID, Name: t.Name, Note: t.Note, Online: d.IsOnline(t.ID), Mappings: []ResourceMapping{}}
		for _, m := range t.Mappings {
			view.Mappings = append(view.Mappings, ResourceMapping{
				Proto:     m.Proto,
				PublicURL: rt.Active[m.ID],
				Local:     joinHostPort(m.LocalIP, m.LocalPort),
				Note:      m.Note,
				Error:     rt.Errors[m.ID],
			})
		}
		out.Tunnels = append(out.Tunnels, view)
	}
	writeJSON(w, http.StatusOK, out)
}

// skillDoc renders the AI skill markdown for the api-key owner.
func (d *Dashboard) skillDoc(w http.ResponseWriter, r *http.Request) {
	if methodMismatch(w, r, http.MethodGet) {
		return
	}
	k, u, ok := d.userFromApiKey(r)
	if !ok {
		writeErr(w, http.StatusUnauthorized, "无效的 API KEY")
		return
	}
	var b strings.Builder
	if err := d.skillTmpl.Execute(&b, map[string]string{
		"BaseURL": baseURL(r),
		"Key":     k.Key,
		"User":    u.Username,
	}); err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.Write([]byte(b.String()))
}

// ---------- client-facing deploy endpoint ----------

func (d *Dashboard) handleDeploy(w http.ResponseWriter, r *http.Request) {
	ip, _, _ := net.SplitHostPort(r.RemoteAddr)
	if !d.deployAllowed(ip) {
		writeErr(w, http.StatusTooManyRequests, "请求过于频繁")
		return
	}
	id := r.URL.Query().Get("id")
	key := r.URL.Query().Get("key")
	if id == "" || key == "" {
		writeErr(w, http.StatusBadRequest, "缺少 id 或 key")
		return
	}
	t := d.store.TunnelByID(id)
	if t == nil || !t.keyMatches(key) {
		writeErr(w, http.StatusForbidden, "隧道 ID 或 KEY 错误")
		return
	}
	if t.Locked {
		writeErr(w, http.StatusForbidden, "隧道已被锁定, 请联系管理员")
		return
	}
	w.Header().Set("Content-Type", "text/yaml; charset=utf-8")
	w.Write([]byte(d.ClientConfigText(t)))
}
